Add new category tokens.

diff --git a/bookmark b/bookmark
--- a/bookmark
+++ b/bookmark
@@ -19,27 +19,29 @@ The default token sequence is "I12".
 Majuscule tokens indicate records appropriate for public use; minuscule tokens indicate private records.
 
 Available Tokens:
-  A  - description or a list of characteristics
+  A  - description or list of characteristics
   B  - code repository or code exemplar
-	C  - communication exchanged like email, IMs, etc
+  C  - communication exchanged like email, IMs, etc
   D  - guide, explanation, tutorial, list or, catalog
   E  - summary, cheatsheet, or overview of the theory or principles of a topic
   F  - library or utility
-	I  - information collected like articles, bookmarks, etc
-	R  - records created like writings, pictures, etc
-	S  - bookmark (like a reference pointer or symlink to an outside reference, but not the reference itself)
-	1  - important documents like backups, finance, taxes, etc
-	2  - writing (a subcategory of -R ?)
-	3  - design and visuals: art, scientific figures, seminar slides, etc
-	4  - life: recipes, productivity, vacations, etc
-	5  - commerce: transactions, returns, insurance, etc
-	6  - government: taxes, identification, papers, etc.
-	7  - maintenance: cars, etc
-	8  - career advancement or transition
-	9  - sysadmin
-	10 - software development of any kind
-	11 - hardware
-	12 - miscellaneous
+  G  - cast, podcast, or screencast
+  H  - hub or portal
+  I  - information collected like articles, bookmarks, etc
+  R  - records created like writings, pictures, etc
+  S  - bookmark (like a reference pointer or symlink to an outside reference, but not the reference itself)
+  1  - important documents like backups, finance, taxes, etc
+  2  - writing (a subcategory of -R ?)
+  3  - design and visuals: art, scientific figures, seminar slides, etc
+  4  - life: recipes, productivity, vacations, etc
+  5  - commerce: transactions, returns, insurance, etc
+  6  - government: taxes, identification, papers, etc.
+  7  - maintenance: cars, etc
+  8  - career advancement or transition
+  9  - sysadmin
+  10 - software development of any kind
+  11 - hardware
+  12 - miscellaneous
 
 END_OF_HELP_MSG
 }
@@ -61,30 +63,30 @@ TS="I10"
 # Colons following the "-@" and "-t" flags indicate that parameters are required.
 while getopts ":@:t:s?" opt; do case $opt in
 
-		# The default URL is gotten from the buffer,
-		# but it can be overridden with the "-@" flag.
-		@) SRC="$OPTARG"
+    # The default URL is gotten from the buffer,
+    # but it can be overridden with the "-@" flag.
+    @) SRC="$OPTARG"
        ;;
 
-		# By default, the resulting document will principally
-		# comprise the html document (in markdown format)
-		# found at the URL ($SRC). However, the "-s" flag
-		# saves only the URL link ($SRC) itself and not the document.
-		s) JUST_SAVE_LINK=true
+    # By default, the resulting document will principally
+    # comprise the html document (in markdown format)
+    # found at the URL ($SRC). However, the "-s" flag
+    # saves only the URL link ($SRC) itself and not the document.
+    s) JUST_SAVE_LINK=true
        ;;
 
-		t) TS="$OPTARG"
+    t) TS="$OPTARG"
        ;;
-	 \?) displayHelpMessage
-		   exit 0
-		   ;;
+   \?) displayHelpMessage
+       exit 0
+       ;;
 
     # An unescaped '?' represents the default setting.
-		?) echo "Invalid Option Specified."
-			 echo "$USAGE" 1>&2
-			 exit 1
-			 ;;
-	esac
+    ?) echo "Invalid Option Specified."
+       echo "$USAGE" 1>&2
+       exit 1
+       ;;
+  esac
 done
 
 # OPTIND should now be the index of the first non-flag-related argument.
@@ -92,7 +94,7 @@ done
 shift $(($OPTIND - 1))
 
 if [[ -z "$SRC" ]]; then
-	SRC="$(xclip -o)"
+  SRC="$(xclip -o)"
 fi
 
 DATE="$( date +%Y%m%d-%H%M%s )"
@@ -104,16 +106,16 @@ fi
 NAME="$DATE"-"$TS"
 
 if [[ "$#" < 1 ]]; then
-	echo "Optimal use of this script requires at least one tag."
+  echo "Optimal use of this script requires at least one tag."
 else
-	for arg in "$@"; do
-		if [ "$arg" = 'help' ]; then
+  for arg in "$@"; do
+    if [ "$arg" = 'help' ]; then
       displayHelpMessage
-			exit 0
-		else
-			NAME="$NAME"."$arg"
-		fi
-	done
+      exit 0
+    else
+      NAME="$NAME"."$arg"
+    fi
+  done
 fi
 
 NAME="$NAME".md
@@ -121,22 +123,22 @@ NAME="$NAME".md
 TGT="$BOOKMARKPATH/$NAME"
 
 if [ -e "$TGT" ]; then
-	echo "File ($TGT) already exists."
-	exit 1;
+  echo "File ($TGT) already exists."
+  exit 1;
 elif $JUST_SAVE_LINK; then
-	echo "Find pertinent document or resource at the following URL:" >> "$TGT"
-	echo "$SRC" >> "$TGT"
+  echo "Find pertinent document or resource at the following URL:" >> "$TGT"
+  echo "$SRC" >> "$TGT"
 else
   echo "$SRC"
-	curl "$SRC" | pandoc -f html -o "$TGT"
+  curl "$SRC" | pandoc -f html -o "$TGT"
   echo >> "$TGT"
-	echo "This markdown document has been converted from the html document located at:" >> "$TGT"
-	echo "$SRC" >> "$TGT"
-	echo "$SRC has been bookmarked at $TGT."
+  echo "This markdown document has been converted from the html document located at:" >> "$TGT"
+  echo "$SRC" >> "$TGT"
+  echo "$SRC has been bookmarked at $TGT."
 fi
 
 for arg in "$@"; do
-	tag set "$TGT" "$arg"
+  tag set "$TGT" "$arg"
 done
 
 exit 0;
